name: prechac_this
description: PrechacThis App.
version: 1.0.0+20
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  bloc: ^8.0.2
  dartx: ^1.0.0
  equatable: ^2.0.3
  flow_builder: ^0.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  formz: ^0.4.0
  fraction: ^4.0.1
  google_fonts: ^2.0.0
  intl: ^0.17.0
  petitparser: ^4.1.0
  select_form_field: ^2.1.0
  trotter: ^2.0.0-dev.1

dev_dependencies:
  bloc_test: ^9.0.2
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0
  very_good_analysis: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
